float32 LeftFootPosX
float32 LeftFootPosY
float32 LeftFootPosZ
float32 LeftFootOrientW
float32 LeftFootOrientX
float32 LeftFootOrienty
float32 LeftFootOrientZ

float32 RightFootPosX
float32 RightFootPosY
float32 RightFootPosZ
float32 RightFootOrientW
float32 RightFootOrientX
float32 RightFootOrienty
float32 RightFootOrientZ

float32 LeftHandPosX
float32 LeftHandPosY
float32 LeftHandPosZ
float32 LeftHandOrientW
float32 LeftHandOrientX
float32 LeftHandOrienty
float32 LeftHandOrientZ

float32 RightHandPosX
float32 RightHandPosY
float32 RightHandPosZ
float32 RightHandOrientW
float32 RightHandOrientX
float32 RightHandOrienty
float32 RightHandOrientZ

uint8 FeetGroundStatus
uint8 FeetSwingStatus
uint8 LeftHandOpStatus
uint8 RightHandOpStatus
uint8 LeftArmStatus
uint8 RightArmStatus
uint32 RobotStatus